"""column current_price removed

Revision ID: 70ecc07c9aa2
Revises: 8a8787e8b35d
Create Date: 2026-01-27 15:35:26.870730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70ecc07c9aa2'
down_revision: Union[str, Sequence[str], None] = '8a8787e8b35d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'current_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('current_price', sa.NUMERIC(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###
