"""column currency added to asset and is_admin removed

Revision ID: 8a8787e8b35d
Revises: d1bda3d1e7c2
Create Date: 2026-01-27 13:44:17.388264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a8787e8b35d'
down_revision: Union[str, Sequence[str], None] = 'd1bda3d1e7c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('currency', sa.String(), nullable=True))
    op.drop_column('customers', 'is_admin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('is_admin', sa.BOOLEAN(), nullable=True))
    op.drop_column('assets', 'currency')
    # ### end Alembic commands ###
