"""column account_balance removed

Revision ID: d1bda3d1e7c2
Revises: a71a35ba7564
Create Date: 2026-01-26 10:02:42.699045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1bda3d1e7c2'
down_revision: Union[str, Sequence[str], None] = 'a71a35ba7564'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'account_balance')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('account_balance', sa.NUMERIC(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###
